# Generated by Django 5.0.4 on 2024-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='sana',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
